# Generated by Django 4.1.7 on 2023-03-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parkingLoader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_reg', models.TextField(max_length=8)),
                ('vehicle_type', models.TextField(choices=[('lorry', 'lorry'), ('large vehicle', 'large vehicle'), ('pickup', 'pickup')], max_length=50)),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('location', models.TextField(max_length=True)),
            ],
        ),
    ]
