# Generated by Django 4.1.7 on 2023-03-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkloader', '0002_alter_parkingloader_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingloader',
            name='vehicle_type',
            field=models.TextField(choices=[('lorry', 'lorry'), ('large vehicle', 'large vehicle'), ('pickup', 'pickup'), ('personal car', 'personal car')], max_length=50),
        ),
    ]
