# Generated by Django 4.1.7 on 2023-03-19 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkloader', '0007_rename_billing_parkingloader_plan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='Billingplan',
            new_name='plan',
        ),
    ]
