# Generated by Django 4.1.7 on 2023-03-20 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkloader', '0008_rename_billingplan_billing_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingloader',
            old_name='car_reg',
            new_name='car_regestration_number',
        ),
    ]
